### ISSUE TITLE
Workflow not running 

### ISSUE THREAD

**Issue by YuFeng0930** [dessant/issue-states#6]
I did move around an existing issue and tried to move it to "Done". But the workflow is not running, and the issue is not closed as well. 

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/56251951/221342226-37b38ca6-6abf-4957-b65f-a5745a147c11.png">

**Comment by diogoSantosDevGit** [comment]
Is it an org repository? Because if it is, apparently there's [no event](https://github.com/dessant/issue-states/issues/2) is fired when a card is moved and the Action is not triggered...

**Comment by dessant** [comment]
Tracking at https://github.com/dessant/issue-states/issues/2#issuecomment-1575137928.
